In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3
import sql

In [97]:
df = pd.read_csv('diabetes.csv')

In [98]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [99]:
df_obesos = df[(df.Age > 50)]
df_obesos

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76,27,0,35.6,0.378,52,1
734,2,105,75,0,0,23.3,0.560,53,0
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [100]:
def Obesidade(BMI):
    if BMI > 30:
        return "1"
    elif BMI < 30:
        return "0"

df_obesos['Obesidade'] = df_obesos['BMI'].map(Obesidade)
display(df_obesos.head())

C:\Users\DNC-PC-138\AppData\Local\Temp\ipykernel_4016\3962507224.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_obesos['Obesidade'] = df_obesos['BMI'].map(Obesidade)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Obesidade
8,2,197,70,45,543,30.5,0.158,53,1,1
9,8,125,96,0,0,0.0,0.232,54,1,0
12,10,139,80,0,0,27.1,1.441,57,0,0
13,1,189,60,23,846,30.1,0.398,59,1,1
14,5,166,72,19,175,25.8,0.587,51,1,0

In [104]:
df_obesos = df[(df_obesos.Obesidade == 1)]
df_obesos

C:\Users\DNC-PC-138\AppData\Local\Temp\ipykernel_4016\1405554241.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_obesos = df[(df_obesos.Obesidade == 1)]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).